#!/usr/bin/env python3
"""
Export a minimal Relativity-compatible load:
- DAT (Concordance) with þ as text qualifier, ¶ for newlines
- OPT (stub) referencing text files (demo)
Inputs:
  - review_set.csv generated by run_pipeline.py
  - out/natives and out/text populated by run_pipeline.py
Config:
  - fields-mapping.yaml (optional; otherwise default mapping)
"""
from __future__ import annotations
import argparse
import csv
import os
from pathlib import Path
from typing import Dict, List

DEFAULT_FIELDS = [
    # (display_name, csv_key)
    ("DOCID", "file_id"),
    ("FROM", "from"),
    ("TO", "to"),
    ("CC", "cc"),
    ("SUBJECT", "subject"),
    ("DATE", "date"),
    ("HASH", "content_hash"),
    ("DUP_OF", "duplicate_of"),
    ("TEXT", "text_path"),
    ("NATIVE", "native_path"),
]

DELIM = "þ"
NEWLINE = "¶"

def parse_args():
    p = argparse.ArgumentParser(description="Export Relativity-style load files.")
    p.add_argument("--input-csv", default="out/review_set.csv")
    p.add_argument("--natives", default="out/natives")
    p.add_argument("--text", default="out/text")
    p.add_argument("--outdir", default="out/relativity")
    return p.parse_args()

def main():
    args = parse_args()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    natives_dir = Path(args.natives)
    text_dir = Path(args.text)
    rows = read_csv(Path(args.input_csv))

    # augment rows with file paths
    for r in rows:
        r["native_path"] = str((natives_dir / f"{r['file_id']}.eml")) if (natives_dir / f"{r['file_id']}.eml").exists() else str((natives_dir / f"{r['file_id']}.json"))
        r["text_path"] = str(text_dir / f"{r['file_id']}.txt")

    write_dat(outdir / "loadfile.dat", rows, DEFAULT_FIELDS)
    write_opt(outdir / "images.opt", rows)

    print(f"Export complete: {outdir.resolve()}")

def read_csv(path: Path) -> List[Dict[str, str]]:
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)

def write_dat(path: Path, rows: List[Dict[str, str]], mapping):
    # Concordance DAT: fields separated by DELIM and wrapped with DELIM.
    headers = [m[0] for m in mapping]
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(DELIM.join(headers) + "\r\n")
        for r in rows:
            vals = [sanitize(str(r.get(csv_key, ""))) for _, csv_key in mapping]
            line = DELIM + (DELIM + DELIM).join(vals) + DELIM + "\r\n"
            f.write(line)

def write_opt(path: Path, rows: List[Dict[str, str]]):
    """
    Simple OPT (image cross-reference). For demo, we reference text files as 'images'.
    Real matters would reference TIFF/PDF images.
    Columns: DocID, Volume, Path, FileName, Page, Type
    """
    with open(path, "w", encoding="utf-8", newline="") as f:
        for r in rows:
            docid = r["file_id"]
            filepath = r["text_path"].replace("\\", "/")
            fname = Path(filepath).name
            line = f"{docid},VOL001,{filepath},{fname},1,Y\r\n"
            f.write(line)

def sanitize(v: str) -> str:
    # Replace newlines with NEWLINE marker per Concordance convention
    return v.replace("\r\n", NEWLINE).replace("\n", NEWLINE).replace(DELIM, " ")

if __name__ == "__main__":
    main()